language: python
python:
  - "3.6"

jdk:
  # Needed for local Neo4j 2.0+
  - oraclejdk8

services:
  # Also works, but can't specify version...
  - neo4j

env:
  # Test across multiple versions of Neo4j:
  - NEO4J_VERSION="3.5.5"

before_install:
  # Install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
  # HACK need to change the password initially; changing it and then reverting:
  - sleep 10  # give Neo4J some time to start

script:
  - python app/run.py
  - python test/test_app.py
